#! /bin/sh

echo What is your website name?
read WEBSITE_NAME

CSS="body {
	background-color: powderblue;
}

h1 {
	color: red;
}"


HTML="<!DOCTYPE html>
<html>
	<head>
		<title>Cards List</title>
		<style>
		$CSS
		</style>
	</head>
	<body>
		<h1>$WEBSITE_NAME</h1>
		<h2>$CSS</h2>
		<p>This was generated by a script shell</p>
	</body>
</html>"

echo $1;

echo "$HTML" > index.html


