#! /bin/sh

echo What is your website name?
read WEBSITE_NAME

HTML="<!DOCTYPE html>
<html>
	<head>
		<title>$WEBSITE_NAME</title>
	</head>
	<body>
		<h1>$WEBSITE_NAME</h1>
		<p>This was generated by a script shell</p>
	</body>
</html>"

echo "$HTML" > index.html


